name: mybreau
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  animations: ^2.0.11
  shared_preferences: ^2.2.2
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.12.2
  image_picker: ^1.2.1
  url_launcher: ^6.3.2
  
  # Package untuk CSV & Export (Sekarang sudah dirapikan, tidak ada duplikat!)
  csv: ^5.1.1
  path_provider: ^2.1.2
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/qris.jpg
    - assets/logo_biro.png


# Konfigurasi Splash Screen
flutter_native_splash:
  color: "#1565C0" # Warna background (Ini putih. Ubah kode hex-nya kalau mau warna lain)
  image: assets/logo_biro.png # Path menuju file logomu
  
  android_12:
    color: "#1565C0"
    image: assets/logo_biro.png

